### ISSUE TITLE
grass_position.py error

### ISSUE THREAD

**Issue by RemiRigal** [LEPAAV/RobotDesherbeur#79]
```
Traceback (most recent call last):
  File "/home/remi/Vacation/G3/src/desherbor_ensta/worlds/grass_position.py", line 50, in <module>
    Grass.get_position()
  File "/home/remi/Vacation/G3/src/desherbor_ensta/worlds/grass_position.py", line 35, in get_position
    x_grass = self.position_robot.x + self.distance_herb*math.cos(self.position_robot.theta + self.theta)
AttributeError: Grass_position instance has no attribute 'theta'
```

**Comment by TilletJ** [comment]
Same issue, cannot weed my garden :(

**Comment by Victorbares** [comment]
Should be working, right now. thanks for your contribution.
